Bug fix

diff --git a/Dockerfile_full b/Dockerfile_full
--- a/Dockerfile_full
+++ b/Dockerfile_full
@@ -1,5 +1,5 @@
 # Reproducible environment for RadixGraph experiments
-FROM ubuntu:20.04
+FROM ubuntu:24.04
 
 ENV DEBIAN_FRONTEND=noninteractive
 WORKDIR /workspace
@@ -7,12 +7,8 @@ WORKDIR /workspace
 # ----------------------------
 # System dependencies
 # ----------------------------
-RUN apt-get update && apt-get install -y software-properties-common \
-    && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
-    && apt-get update \
-    && apt-get install -y gcc-11 g++-11
-
 RUN apt-get update && apt-get install -y \
+    gcc-11 g++-11 \
     build-essential \
     cmake \
     git \
@@ -22,6 +18,7 @@ RUN apt-get update && apt-get install -y \
     zlib1g-dev \
     libsqlite3-dev \
     libpapi-dev \
+    libjemalloc-dev \
     libtbb-dev \
     autoconf automake \
     python3 python3-pip python3-dev \
@@ -30,6 +27,19 @@ RUN apt-get update && apt-get install -y \
 # Make gcc-11 / g++-11 default (matches notebook)
 RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && \
     update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
+
+# # Install TBB
+# RUN wget https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.1.0.tar.gz && \
+#   tar -xzf v2022.1.0.tar.gz && \
+#   cd oneTBB-2022.1.0 && \
+#   mkdir build && cd build && \
+#   cmake .. -DCMAKE_BUILD_TYPE=Release && \
+#   make -j$(nproc) && \
+#   make install
+
+# # Check whether TBB is installed correctly
+# RUN nm /usr/lib/x86_64-linux-gnu/libtbb.so | grep -q "TBB_runtime_interface_version" || \
+#     (echo "Error: TBB symbol TBB_runtime_interface_version not found!" >&2 && exit 1)
 
 # ----------------------------
 # Python dependencies
